# Generated by Django 4.2.7 on 2025-09-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Our Restaurant', max_length=100)),
                ('total_tables', models.PositiveIntegerField(default=20)),
                ('currently_occupied_tables', models.PositiveIntegerField(default=15)),
                ('avg_dine_in_duration_minutes', models.PositiveIntegerField(default=45)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='estimated_arrival_time',
        ),
        migrations.AddField(
            model_name='order',
            name='queue_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='target_arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IN_QUEUE', 'In Queue'), ('AWAITING_ARRIVAL', 'Awaiting Arrival'), ('RECEIVED', 'Order Received'), ('PREPARING', 'Preparing'), ('READY', 'Ready for Seating'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='IN_QUEUE', max_length=20),
        ),
    ]
